trigger:
- main

variables:
- group: cypress-env

pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    echo '{
      "HACKATHON_USER": "$(HACKATHON_USER)",
      "HACKATHON_VALID_PASS": "$(HACKATHON_VALID_PASS)",
      "HACKATHON_INVALID_PASS": "$(HACKATHON_INVALID_PASS)"
    }' > cypress.env.json
  displayName: 'Create cypress.env.json file'

- script: |
    npx cypress verify
  displayName: 'Verify Cypress install'

- script: |
    npm run test
  displayName: 'Run Cypress tests'